package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "config_proto",
    deps = [
        ":config_lib",
    ],
)

proto_library(
    name = "config_lib",
    srcs = ["config.proto"],
    deps = [
    ],
)